### ISSUE TITLE
[BUG] Feature boxes are not responsive.

### ISSUE THREAD

**Issue by viralRupani** [Codepire/community-app-client#2]
**Describe the bug**
Feature description is overlapping in small-size devices.

**To Reproduce**
1. Open Chrome Developer Tools.
2. Select dimensions to responsive and shrink the screen horizontally, or select any small device in dimensions.
3. Scroll down to Features

**Expected behavior**
The entire description should fit in that box properly. we can use properties like height and min-height for that.

**Screenshots**
![image](https://github.com/Codepire/community-app-client/assets/87006810/f4b22d19-3531-44ef-8787-a6dbb200a0e8)

**Comment by CarlosEGCH** [comment]
Hey! Could you please assign this issue to me? :)
