### ISSUE TITLE
[FEAT] Good Footer needed!

### ISSUE THREAD

**Issue by viralRupani** [Codepire/community-app-client#3]
**Describe the solution you'd like**

Create a good footer in the footer area. use your creativity.
No need to link text in the footer for now.
Add some animations, and effects if possible.
A good one will be accepted.

**Some references.**
1) [Discord](https://discord.com/)
![image](https://github.com/Codepire/community-app-client/assets/87006810/1bd55bb7-b93d-446b-affa-731126a52738)

2) [Next Js](https://nextjs.org/)
![image](https://github.com/Codepire/community-app-client/assets/87006810/7706d677-4f53-43ac-9887-5f24b1aa6518)

**Comment by AadiXC0DE** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by Sky-De** [comment]
@viralRupani assign this to me, then i will start working on that
